### ISSUE TITLE
On sequelize model option Paranoid: true, cursor generating different query.

### ISSUE THREAD

**Issue by molagbal01** [Kaltsoon/sequelize-cursor-pagination#14]
Hi,

On sequelize model, if paranoid is set to true explicitly, cursor is generating different query.

 When paranoid set to false: 

`SELECT `id`, `visitor_id`, `visiting_id`, `property_id`, `verification_code`, `verification_token`, `createdAt`, `updatedAt`, `deletedAt`, `unit_id`, `have_vehicle`, `vehicle_no`, `vehicle_type`, `purpose` FROM `regular_visitors` AS `regular_visitors` WHERE (`regular_visitors`.`id` > 169 AND `regular_visitors`.`property_id` = 32) ORDER BY `regular_visitors`.`id` LIMIT 6;`

when paranoid set to true:

`SELECT `id`, `visitor_id`, `visiting_id`, `property_id`, `verification_code`, `verification_token`, `createdAt`, `updatedAt`, `deletedAt`, `unit_id`, `have_vehicle`, `vehicle_no`, `vehicle_type`, `purpose` FROM `regular_visitors` AS `regular_visitors` WHERE (`regular_visitors`.`deletedAt` > CURRENT_TIMESTAMP OR `regular_visitors`.`deletedAt` IS NULL) ORDER BY `regular_visitors`.`id` LIMIT 6;`

Thanks in advance.

**Comment by Kaltsoon** [comment]
Could you elaborate, what is the problem? As far as I understand, when the `paranoid` option is set to `true`, Sequelize filters out rows, which have been marked deleted with the `deletedAt` column. This is the reason why the generated query is different, not because of this package.
