### ISSUE TITLE
Add UUID support

### ISSUE THREAD

**Issue by hartherbert** [Kaltsoon/sequelize-cursor-pagination#16]
Hey @Kaltsoon this library is great! I'm trying to implement it but I've now seen that it is not possible to have UUID's as primary key (as postgresql allows you to) bcs the paginationQuery orders only by Op.gt or Op.lt .

Would be great if this could be done.
If I have time I will create a pull request.

Cheers

**Comment by Kaltsoon** [comment]
Hi @hobbydevs, glad to hear, that you like the library! Could you clarify why it isn't possible to use the library with UUID primary keys? Doesn't Postgre's UUID type support `>` and `<` comparison operators?
