### ISSUE TITLE
multiple order generates invalid query

### ISSUE THREAD

**Issue by mrofia** [Kaltsoon/sequelize-cursor-pagination#17]
As far as i can see in the test, this extension only allows for single ordering options.

```
test('paginates correctly when findAll attributes are provided', async t => {
  const data = await generateTestData();

    let pagination = await Test.paginate({ order: [ 'counter', 'DESC' ], limit: 5, attributes: ['counter'], paginationField: 'counter' });
    t.deepEqual(pagination.results.map(r => r.counter), [ 4, 4, 3, 2, 1 ]);
});
```

However I need multiple stage of ordering for my business logic.
The code below is accepted in sequelize, but not accepted in this extension
```
order: [
                ['Promo', 'dateStart', 'DESC'],
                ['AcademyCourse','dateAdded', 'DESC']
            ]
```

The above logic is necessary for me, because i need to show OLD data if it's included in a newer promo.  

Another question also arise, will this require me to change the pagination field somehow? or do i need to tackle this issue by reorganizing my db structure somehow?

**Comment by Kaltsoon** [comment]
Ordering with multiple fields could be problematic because only the primary key and possible pagination key is serialized into the cursor. In your case, I think you do something like this:

```javascript
Model.paginate({ order: ['dateStart', 'DESC'], limit: 100, paginationField: 'dateAdded', desc: true });
```

In this case, the `order` attribute would be:

```javascript
[
  ['dateStart', 'DESC'],
  ['dateAdded', 'DESC'],
  [primaryKeyField],
]
```

However, if you have multiple rows with the same `dateStart` and `dateAdded` values (which, I guess is very unlikely) there could be some issues.

**Comment by blacksmoke26** [comment]
Same issue.
```
BY "".CAST(("meta"#>>'{forSale}') AS BOOLEAN) ASC NULLS LAST, "Property"."id" LIMIT 11
```

**Comment by blacksmoke26** [comment]
Still same issue.

```js
order : [
  [CAST(("meta"#>>'{something}') AS BOOLEAN), 'ASC NULLS LAST'],
  ['user_id', 'ASC'],
],
```

```
BY "".CAST(("meta"#>>'{something}') AS BOOLEAN) ASC NULLS LAST, "Post"."id" LIMIT 11
```

What to do?

**Comment by ngels** [comment]
I want to do pagination with link to specific page like. the front end will look like this  |<<|1|2|3|4|5|>>|
