### ISSUE TITLE
Option to override ordering parameters

### ISSUE THREAD

**Issue by jadhavmanoj** [Kaltsoon/sequelize-cursor-pagination#46]
Currently, ASC ordering is used by default on `primaryKeyField`. When we use UUID, it might produce unexpected results when combined with other ordering parameters. In short I want to skip ordering on `primaryKeyField`.

Is there a way to override the ordering field? 

I can see similar issue reported #24 and closed without any comment 🤔

**Comment by Kaltsoon** [comment]
What's the unexpected result? Could you share some code and what kind of output do you expect? The idea of the primary key field is to ensure that there's and unique column in the ordering. There could be an option to override this behavior, but I would first like to know what's the issue with the current behavior. 

I reopened that issue, I don't quite remember why I closed it.

**Comment by Kaltsoon** [comment]
Version 2.4.0 now has `omitPrimaryKeyFromOrder` which allows omitting the primary key field from the order.

**Comment by jadhavmanoj** [comment]
Thanks @Kaltsoon for the reply. `omitPrimaryKeyFromOrder` this really helpful. 

What's the unexpected result? Could you share some code and what kind of output do you expect? The idea of the primary key field is to ensure that there's and unique column in the ordering. There could be an option to override this behavior, but I would first like to know what's the issue with the current behavior.
--- The sample response provided in  #24 . I hope that will help you to understand behaviour.

**Comment by Kaltsoon** [comment]
Cool! I guess I won't dig this any deeper for now if `omitPrimaryKeyFromOrder` solves this issue.
