### ISSUE TITLE
Support ordering with DESC / ASC  NULL FIRST

### ISSUE THREAD

**Issue by jadhavmanoj** [Kaltsoon/sequelize-cursor-pagination#59]
When we pass `DESC NULL FIRST` in order list, it choose different operator & unexpected data returns. 

Probable fix for this is - [src/utils.ts](https://github.com/Kaltsoon/sequelize-cursor-pagination/blob/db060b947f1faa14a176968bc6bbbda5adcf2841/src/utils.ts#L104)

```
const currentOp = order[0][1].toLowerCase().split(" ")[0] === 'desc' ? Op.lt : Op.gt;
```

Let me know if you have any other suggestion. So I will create a PR.

**Comment by Kaltsoon** [comment]
Sounds good!
